# Generated by Django 4.1.4 on 2022-12-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='instructions',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
