# Generated by Django 4.1.4 on 2022-12-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_description_alter_post_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('Vietnam', 'Vietnam'), ('Laos', 'Laos'), ('Cambodia', 'Cambodia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
