# Generated by Django 4.1.4 on 2022-12-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_foodtype_message_post_delete_userrecipe_message_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nameRecipes',
            new_name='title',
        ),
    ]
